radiohead = Artist.create!(name: "Radiohead")
aphex_twin = Artist.create!(name: "Aphex Twin")
daft_punk = Artist.create!(name: "Daft Punk")

Song.create!(title: "Get Lucky", artist: daft_punk)
Song.create!(title: "One More Time", artist: daft_punk)
Song.create!(title: "Robot Rock", artist: daft_punk)
Song.create!(title: "Human After All", artist: daft_punk)
Song.create!(title: "Paranoid Android", artist: radiohead)
Song.create!(title: "Reckoner", artist: radiohead)
Song.create!(title: "15 Step", artist: radiohead)
Song.create!(title: "4", artist: aphex_twin)
Song.create!(title: "Acrid Avid Jam Shred", artist: aphex_twin)
Song.create!(title: "Alberto Balsalm", artist: aphex_twin)
