joni = Artist.create!(name: "Joni Mitchell")
joni.songs.create!(title: "Amelia")
joni.songs.create!(title: "Court and Spark")
joni.songs.create!(title: "A Taste of You")
thedan = Artist.create!(name: "Steely Dan")
thedan.songs.create!(title: "FM")
thedan.songs.create!(title: "Your Gold Teeth II")
thedan.songs.create!(title: "Hatian Divorce")
